### ISSUE TITLE
Cant login with a new user

### ISSUE THREAD

**Issue by VitaliKaiser** [polyaxon/polyaxon-cli#3]
I created a new user and activated it with a superuser.

When trying to login I got this error:

```
polyaxon login --username=testuser
Please enter your password: 

Could not login.


400 on http://*********:**/api/v1/users/token/.
```

If I login with the superuser everything works just fine. Also typing in a wrong password results in an other error message (as expected).

Best,
Vitali

**Comment by mouradmourafiq** [comment]
Hi @VitaliKaiser,

I don't believe that there's another error message for wrong passwords.

Did you try to login with the same user in the dashboard to see if it's working?

Can you try to:
  1. create a new user
  2. activate the user
  3. login with the new user

Thanks,
M

**Comment by VitaliKaiser** [comment]
ok, this is the result:

1. create a new user
Response from the webinterface is: "Your account was created successfully. Please reach out to your superuser/admin to activate your account."

2. activate the user
```
polyaxon user activate dummy
User `dummy` was activated successfully.
```

3. login with new user in the dashboard
Does not work: "Unable to log in with provided credentials."

Executing `polyaxon login --username=dummy` with the wrong password results in:
```
Please enter your password: 

Could not login.


400 on http://35.205.201.125:80/api/v1/users/token/.
```

Executing it with the correct password results in:
```
Please enter your password: 
Request to http://35.205.201.125:80/api/v1/users/ failed with status code 500. 
Reason: <h1>Server Error (500)</h1>

Could not load user info.


Error message `500 on http://35.205.201.125:80/api/v1/users/.`.
```

**Comment by VitaliKaiser** [comment]
BTW: Login with the root account works without problems

**Comment by mouradmourafiq** [comment]
Yes I think I know what is the issue, and it's been fixed. The release that I am preparing has the fix.

Sorry for the trouble.

**Comment by VitaliKaiser** [comment]
The fix worked! Thanks again. I am closing this issue now.
