### ISSUE TITLE
project init should not update existing .polyaxonignore

### ISSUE THREAD

**Issue by rogerzklotz** [polyaxon/polyaxon-cli#6]
### Describe the bug
Polyaxon recreates .polyaxonignore file when performing `polyaxon init PROJECT`

### To Reproduce
Create .polyaxonignore file with non-default content (add your own files to ignore)
Run `polyaxon init project-name`, verify `.polyaxonignore` has changed back to the "default" values.

### Expected behavior
It should behave like polyaxonfile.yml and leave the file untouched if it already exists

**Comment by mouradmourafiq** [comment]
This will be part of today's release
